source "https://rubygems.org"
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby "3.1.2"
gem "bcrypt", "~> 3.1.7"
gem "jwt"
gem "puma", "~> 5.0"
gem "rack-cors"
gem "rails", "~> 7.0.4", ">= 7.0.4.2"
gem "sqlite3", "~> 1.4"
gem "tzinfo-data", platforms: %i[ mingw mswin x64_mingw jruby ]

group :development, :test do
  gem "byebug", platforms: %i[ mri mingw x64_mingw ]
end


